#!/usr/bin/env python3
"""Run the DayDine market pipeline for a configured town/area.

This is the generic, repo-driven entry point for adding or refreshing a market.
It uses data/ranking_areas.json as the control file and avoids hard-coded
Stratford logic.

Current scope:
- offline/deterministic pipeline orchestration;
- validates configured market and source files;
- optionally runs V4 scoring from committed establishment/enrichment files;
- builds the configured area ranking JSON;
- regenerates market-readiness assets;
- writes an auditable pipeline summary.

External collection/enrichment is intentionally not done here yet. If the source
establishment file is missing, this script exits with a clear blocked status and
next steps rather than pretending the market can be published.

Examples:
    python scripts/run_market_pipeline.py --market stratford-upon-avon
    python scripts/run_market_pipeline.py --market leamington-spa --dry-run
    python scripts/run_market_pipeline.py --market oxford --allow-missing-source
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
AREAS_FILE = ROOT / "data" / "ranking_areas.json"
PIPELINE_OUT_DIR = ROOT / "outputs" / "market-pipeline"
READINESS_DIR = ROOT / "assets" / "market-readiness"
RANKINGS_DIR = ROOT / "assets" / "rankings"


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", str(value).lower()).strip("-")


def norm(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", " ", str(value or "").lower()).strip()


def read_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


def load_areas() -> list[dict[str, Any]]:
    config = read_json(AREAS_FILE, {"areas": []}) or {"areas": []}
    return [area for area in config.get("areas", []) if isinstance(area, dict)]


def data_prefix_for_area(area: dict[str, Any]) -> str:
    if area.get("data_source_prefix"):
        return str(area["data_source_prefix"])
    la = norm(area.get("la_name"))
    slug = norm(area.get("slug"))
    if "stratford" in la or "stratford" in slug:
        return "stratford"
    if "leamington" in la or "leamington" in slug:
        return "leamington"
    return slugify(area.get("slug") or area.get("display_name") or "market")


def match_area(area: dict[str, Any], market: str) -> bool:
    wanted = slugify(market)
    aliases = [
        area.get("slug"),
        area.get("display_name"),
        area.get("la_name"),
        area.get("data_source_prefix"),
        *(area.get("legacy_slugs") or []),
    ]
    return wanted in {slugify(str(a)) for a in aliases if a}


def resolve_area(market: str) -> dict[str, Any]:
    matches = [area for area in load_areas() if match_area(area, market)]
    if not matches:
        known = ", ".join(sorted(str(a.get("slug")) for a in load_areas() if a.get("slug")))
        raise SystemExit(f"Unknown market '{market}'. Add it to data/ranking_areas.json first. Known: {known}")
    public_matches = [m for m in matches if m.get("public")]
    return public_matches[0] if public_matches else matches[0]


def areas_for_prefix(prefix: str) -> list[dict[str, Any]]:
    return [area for area in load_areas() if data_prefix_for_area(area) == prefix]


def file_plan(prefix: str) -> dict[str, str]:
    return {
        "establishments": f"{prefix}_establishments.json",
        "scores_json": f"{prefix}_rcs_v4_scores.json",
        "scores_csv": f"{prefix}_rcs_v4_scores.csv",
        "menus": f"{prefix}_menus.json",
        "editorial": f"{prefix}_editorial.json",
        "companies_house": f"{prefix}_companies_house_risk.json",
        "companies_house_review_audit": f"{prefix}_companies_house_review_audit.json",
        "entity_resolution_report": f"{prefix}_entity_resolution_report.json",
    }


def existing_optional(path: str) -> str | None:
    return path if (ROOT / path).exists() else None


def run(cmd: list[str], dry_run: bool, steps: list[dict[str, Any]]) -> int:
    steps.append({"cmd": cmd, "dry_run": dry_run})
    print("$ " + " ".join(cmd))
    if dry_run:
        return 0
    completed = subprocess.run(cmd, cwd=ROOT)
    steps[-1]["returncode"] = completed.returncode
    return completed.returncode


def build_single_source_area_config(prefix: str, areas: list[dict[str, Any]], out_path: Path) -> None:
    payload = {
        "_note": f"Generated by scripts/run_market_pipeline.py for data_source_prefix={prefix}. Do not edit directly.",
        "areas": areas,
    }
    write_json(out_path, payload)


def status_from_readiness(market: str) -> str:
    path = READINESS_DIR / f"{market}.json"
    data = read_json(path, {}) or {}
    return str(data.get("status") or "unknown")


def build_summary(
    area: dict[str, Any],
    prefix: str,
    files: dict[str, str],
    source_areas: list[dict[str, Any]],
    status: str,
    steps: list[dict[str, Any]],
    errors: list[str],
    warnings: list[str],
) -> dict[str, Any]:
    slug = str(area.get("slug"))
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "market": slug,
        "display_name": area.get("display_name"),
        "data_source_prefix": prefix,
        "status": status,
        "area": area,
        "source_areas": [a.get("slug") for a in source_areas],
        "files": {key: value for key, value in files.items()},
        "outputs": {
            "ranking": str((RANKINGS_DIR / f"{slug}.json").relative_to(ROOT)),
            "readiness": str((READINESS_DIR / f"{slug}.json").relative_to(ROOT)),
            "summary": str((PIPELINE_OUT_DIR / f"{slug}.json").relative_to(ROOT)),
        },
        "steps": steps,
        "errors": errors,
        "warnings": warnings,
        "next_steps": next_steps_for(status, prefix, files),
    }


def next_steps_for(status: str, prefix: str, files: dict[str, str]) -> list[str]:
    if status == "blocked_missing_source":
        return [
            f"Create or collect {files['establishments']} for data_source_prefix '{prefix}'.",
            "Add a market entry to data/ranking_areas.json with slug, display_name, la_name, region, centre/radius for public town markets, and data_source_prefix.",
            "Run enrichment/collection workflows for FSA/FHRS, Google Places and optional TripAdvisor/Companies House inputs.",
            f"Re-run: python scripts/run_market_pipeline.py --market <slug>",
        ]
    if status == "blocked_pipeline_error":
        return [
            "Inspect the failed command in outputs/market-pipeline/<market>.json.",
            "Fix source data, scoring inputs or ranking config, then re-run the same command.",
        ]
    return [
        "Review /admin/markets and the generated readiness JSON.",
        "Check famous/local venues manually before using the market commercially.",
        "If status is warning, clear or explicitly accept the listed warnings before broad launch.",
    ]


def run_pipeline(args: argparse.Namespace) -> int:
    area = resolve_area(args.market)
    slug = str(area["slug"])
    prefix = data_prefix_for_area(area)
    source_areas = areas_for_prefix(prefix)
    files = file_plan(prefix)
    steps: list[dict[str, Any]] = []
    errors: list[str] = []
    warnings: list[str] = []

    establishments_path = ROOT / files["establishments"]
    scores_path = ROOT / files["scores_json"]

    if not establishments_path.exists():
        errors.append(f"Missing source establishment file: {files['establishments']}")
        status = "blocked_missing_source"
        summary = build_summary(area, prefix, files, source_areas, status, steps, errors, warnings)
        write_json(PIPELINE_OUT_DIR / f"{slug}.json", summary)
        print(json.dumps(summary, indent=2, ensure_ascii=False))
        return 0 if args.allow_missing_source else 1

    if not scores_path.exists() or args.force_score:
        cmd = [
            sys.executable,
            "scripts/run_v4_scoring_with_risk.py",
            "--input", files["establishments"],
            "--out-json", files["scores_json"],
            "--out-csv", files["scores_csv"],
            "--companies-house-review-audit", files["companies_house_review_audit"],
        ]
        if existing_optional(files["menus"]):
            cmd.extend(["--menus", files["menus"]])
        else:
            warnings.append(f"Optional menus file not found: {files['menus']}")
        if existing_optional(files["editorial"]):
            cmd.extend(["--editorial", files["editorial"]])
        else:
            warnings.append(f"Optional editorial file not found: {files['editorial']}")
        if existing_optional(files["companies_house"]):
            cmd.extend(["--companies-house", files["companies_house"]])
        else:
            warnings.append(f"Optional Companies House risk file not found: {files['companies_house']}")
        rc = run(cmd, args.dry_run, steps)
        if rc != 0:
            errors.append("V4 scoring failed")
    else:
        steps.append({"cmd": ["reuse", files["scores_json"]], "returncode": 0})

    generated_areas = ROOT / "outputs" / "market-pipeline" / f"{prefix}_ranking_areas.generated.json"
    build_single_source_area_config(prefix, source_areas, generated_areas)
    rc = run([
        sys.executable,
        "scripts/build_area_rankings_v4.py",
        "--scores", files["scores_json"],
        "--establishments", files["establishments"],
        "--areas", str(generated_areas.relative_to(ROOT)),
    ], args.dry_run, steps)
    if rc != 0:
        errors.append("Area ranking build failed")

    rc = run([sys.executable, "scripts/generate_market_readiness.py"], args.dry_run, steps)
    if rc != 0:
        errors.append("Market readiness generation failed")

    status = "blocked_pipeline_error" if errors else (status_from_readiness(slug) if not args.dry_run else "dry_run")
    summary = build_summary(area, prefix, files, source_areas, status, steps, errors, warnings)
    write_json(PIPELINE_OUT_DIR / f"{slug}.json", summary)
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 1 if errors else 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the DayDine market pipeline for a configured town/area")
    parser.add_argument("--market", required=True, help="Market slug/display name from data/ranking_areas.json")
    parser.add_argument("--force-score", action="store_true", help="Re-run V4 scoring even if score JSON exists")
    parser.add_argument("--dry-run", action="store_true", help="Print the commands and write a summary without executing pipeline commands")
    parser.add_argument("--allow-missing-source", action="store_true", help="Exit 0 and write a blocked summary if source establishments are missing")
    args = parser.parse_args()
    return run_pipeline(args)


if __name__ == "__main__":
    raise SystemExit(main())
