"""
operator_intelligence/report_generator.py — Report Assembly + QA

Assembles monthly/quarterly reports from section builders,
validates against report_spec quality rules, and generates
QA companion artifacts.
"""

import csv
import json
import os
from datetime import datetime

from operator_intelligence.report_spec import (
    detect_report_mode, validate_report, generate_qa_artifact,
)
from operator_intelligence.builders import (
    build_executive_summary, build_scorecard,
    build_performance_diagnosis, build_commercial_diagnosis,
    build_review_intelligence, build_review_appendices,
    build_watch_list, build_what_not_to_do,
    build_recommendation_tracker, build_competitive_market_intelligence,
    build_data_coverage,
    build_management_priorities, build_market_position,
    build_dimension_diagnosis, build_public_vs_reality,
    build_demand_capture_audit, build_monitoring_plan,
    build_evidence_appendix,
    build_known_for, build_protect_improve_ignore,
)

DIM_ORDER = ["experience", "visibility", "trust", "conversion", "prestige"]


# ---------------------------------------------------------------------------
# Monthly Report Assembly — proposition-led, business-language-first
# ---------------------------------------------------------------------------

def generate_monthly_report(venue_name, month_str, scorecard, deltas,
                            benchmarks, review_intel, review_delta,
                            recs, conditional_blocks=None, venue_rec=None):
    """Assemble full monthly report from builders. Returns (report_text, qa_dict).

    Report structure: leads with leaks/actions/risk, then covers 4 commercial
    lenses (Demand Capture, Proposition & Guest Signal, Trust & Public Risk,
    Competitive Market Intelligence), then supporting score detail, then tracking.
    """
    mode = detect_report_mode(review_intel)
    venue_rec = venue_rec or {}
    L = []
    w = L.append

    # --- Lead: leaks / actions / risk / what not to do ---
    # 1. Executive Summary (actions-led, score secondary)
    build_executive_summary(w, venue_name, month_str, mode, scorecard,
                            deltas, benchmarks, review_intel, recs)
    # 2. What This Venue Is Becoming Known For
    build_known_for(w, venue_name, scorecard, benchmarks, review_intel)
    # 3. Management Priorities
    build_management_priorities(w, scorecard, deltas, benchmarks, recs, venue_rec=venue_rec)
    # 4. Protect / Improve / Ignore
    build_protect_improve_ignore(w, scorecard, deltas, benchmarks, review_intel, recs)

    # --- Lens 1: Demand Capture ---
    # 5. Demand Capture Audit
    build_demand_capture_audit(w, scorecard, venue_rec, benchmarks=benchmarks,
                              review_intel=review_intel)

    # --- Lens 2: Proposition & Guest Signal ---
    # 6. Commercial Diagnosis (bottleneck, positioning, revenue leakage)
    build_commercial_diagnosis(w, scorecard, deltas, benchmarks, review_intel)
    # 7. Review & Reputation Intelligence
    build_review_intelligence(w, mode, review_intel, review_delta, month_str=month_str)

    # --- Lens 3: Trust & Public Risk ---
    # 8. Public Proof vs Operational Reality
    build_public_vs_reality(w, scorecard)

    # --- Lens 4: Competitive Market Intelligence (mandatory) ---
    # 9. Competitive Market Intelligence
    build_competitive_market_intelligence(w, scorecard, benchmarks, conditional_blocks)
    # 10. Market Position (detailed 3-ring peer analysis)
    build_market_position(w, scorecard, benchmarks, venue_rec=venue_rec)

    # --- Score detail (supporting, not driving) ---
    # 11. Dimension Scorecard (compact table, prestige demoted)
    build_scorecard(w, scorecard, deltas, benchmarks)
    # 12. Dimension-by-Dimension Diagnosis
    build_dimension_diagnosis(w, scorecard, deltas, benchmarks)

    # --- Tracking and monitoring ---
    # 13. Watch List
    build_watch_list(w, recs)
    # 14. What Not to Do
    build_what_not_to_do(w, recs)
    # 15. Implementation Framework (replaces Recommendation Tracker)
    build_recommendation_tracker(w, recs, month_str=month_str)
    # 16. Next-Month Monitoring Plan (external leading indicators)
    build_monitoring_plan(w, scorecard, recs)
    # 17. Data Coverage & Confidence
    build_data_coverage(w, scorecard, review_intel)
    # 18. Evidence Appendix
    build_evidence_appendix(w, scorecard, venue_rec)
    # 19. Review-by-Review Summary + Full Review Text Appendix
    build_review_appendices(w, review_intel)

    w("")
    w(f"*Report generated by DayDine v3.3 — {month_str}*")

    report_text = "\n".join(L)

    # Validate
    validation = validate_report(report_text, mode, recs, review_intel, scorecard)

    # QA artifact
    qa = generate_qa_artifact(venue_name, month_str, mode, report_text,
                              validation, review_intel, recs, scorecard)

    return report_text, qa


# ---------------------------------------------------------------------------
# JSON / CSV
# ---------------------------------------------------------------------------

def generate_monthly_json(venue_name, month_str, scorecard, deltas, recs):
    return {
        "venue": venue_name, "month": month_str,
        "scorecard": {k: scorecard.get(k) for k in DIM_ORDER + ["overall"]},
        "deltas": deltas,
        "priority_actions": [
            {"title": a["title"], "status": a["status"],
             "priority": a["priority_score"], "dimension": a["dimension"]}
            for a in recs.get("priority_actions", [])
        ],
        "watch_items": [
            {"title": wa["title"], "status": wa["status"]}
            for wa in recs.get("watch_items", [])
        ],
        "active_recommendations": sum(
            1 for r in recs.get("all_recs", [])
            if r.get("status") not in ("resolved", "dropped", "completed")),
    }


def write_monthly_csv_row(venue_name, month_str, scorecard, csv_path):
    fields = ["month", "venue"] + DIM_ORDER + ["overall"]
    row = {"month": month_str, "venue": venue_name}
    for dim in DIM_ORDER + ["overall"]:
        row[dim] = scorecard.get(dim)
    write_header = not os.path.exists(csv_path)
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


# ---------------------------------------------------------------------------
# Quarterly
# ---------------------------------------------------------------------------

def generate_quarterly_report(venue_name, quarter_str, monthly_cards, recs_history):
    L = []
    w = L.append
    w(f"# Quarterly Strategic Review — {venue_name}")
    w(f"*{quarter_str} | DayDine Premium*\n---\n")
    months = sorted(monthly_cards.keys())
    if not months:
        w("*No monthly data available.*")
        return "\n".join(L)
    w("## Dimension Trends\n")
    w("| Dimension | " + " | ".join(months) + " | Trend |")
    w("|-----------|" + "|".join(["------:" for _ in months]) + "|-------|")
    for dim in DIM_ORDER + ["overall"]:
        vals = [monthly_cards[m].get(dim) for m in months]
        strs = [f"{v:.1f}" if v is not None else "—" for v in vals]
        avail = [v for v in vals if v is not None]
        trend = "—"
        if len(avail) >= 2:
            d = avail[-1] - avail[0]
            trend = "▲" if d > 0.3 else "▼" if d < -0.3 else "→"
        w(f"| {dim.title()} | " + " | ".join(strs) + f" | {trend} |")
    w("")
    if recs_history:
        w("## Recommendation Outcomes\n")
        res = sum(1 for r in recs_history if r.get("status") in ("resolved", "completed"))
        act = sum(1 for r in recs_history if r.get("status") in ("new", "ongoing", "escalated"))
        w(f"- **{res}** resolved/completed, **{act}** still active")
    w(f"\n*DayDine Operator Intelligence v2.0*")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Conditional blocks
# ---------------------------------------------------------------------------

def generate_conditional_blocks(venue, scorecard, benchmarks):
    blocks = []
    ring1 = benchmarks.get("ring1_local", {}) if benchmarks else {}
    if ring1.get("peer_count", 0) >= 10:
        blocks.append({"title": "Competitive Density Alert",
            "content": f"{ring1['peer_count']} direct competitors within 5mi. Differentiation critical."})
    fsa = scorecard.get("fsa_rating")
    if fsa is not None and int(fsa) <= 3:
        blocks.append({"title": "Compliance Risk",
            "content": f"FSA {fsa} caps Trust score and may suppress Google visibility."})
    vis = scorecard.get("visibility")
    if vis is not None and vis < 4.0:
        blocks.append({"title": "Visibility Gap",
            "content": "Online visibility significantly below average. Prioritise GBP and reviews."})
    return blocks
