"""
operator_intelligence/report_generator.py — Report Assembly + QA

Assembles monthly/quarterly reports from section builders,
validates against report_spec quality rules, and generates
QA companion artifacts.
"""

import csv
import json
import os
from datetime import datetime

from operator_intelligence.report_spec import (
    detect_report_mode, validate_report, generate_qa_artifact,
)
from operator_intelligence.builders import (
    build_executive_summary, build_scorecard,
    build_performance_diagnosis, build_commercial_diagnosis,
    build_review_intelligence, build_priority_actions,
    build_watch_list, build_what_not_to_do,
    build_recommendation_tracker, build_conditional_intelligence,
    build_data_coverage,
)

DIM_ORDER = ["experience", "visibility", "trust", "conversion", "prestige"]


# ---------------------------------------------------------------------------
# Monthly Report Assembly
# ---------------------------------------------------------------------------

def generate_monthly_report(venue_name, month_str, scorecard, deltas,
                            benchmarks, review_intel, review_delta,
                            recs, conditional_blocks=None):
    """Assemble monthly report from builders. Returns (report_text, qa_dict)."""
    mode = detect_report_mode(review_intel)
    L = []
    w = L.append

    build_executive_summary(w, venue_name, month_str, mode, scorecard,
                            deltas, benchmarks, review_intel, recs)
    build_scorecard(w, scorecard, deltas, benchmarks)
    build_performance_diagnosis(w, scorecard, deltas, benchmarks, review_intel)
    build_review_intelligence(w, mode, review_intel, review_delta)
    build_commercial_diagnosis(w, scorecard, deltas, benchmarks, review_intel)
    build_priority_actions(w, recs)
    build_watch_list(w, recs)
    build_what_not_to_do(w, recs)
    build_recommendation_tracker(w, recs)
    build_conditional_intelligence(w, conditional_blocks)
    build_data_coverage(w, scorecard, review_intel)

    w("")
    w(f"*Report generated by DayDine Operator Intelligence v2.0 — {month_str}*")

    report_text = "\n".join(L)

    # Validate
    validation = validate_report(report_text, mode, recs, review_intel)

    # QA artifact
    qa = generate_qa_artifact(venue_name, month_str, mode, report_text,
                              validation, review_intel, recs, scorecard)

    return report_text, qa


# ---------------------------------------------------------------------------
# JSON / CSV
# ---------------------------------------------------------------------------

def generate_monthly_json(venue_name, month_str, scorecard, deltas, recs):
    return {
        "venue": venue_name, "month": month_str,
        "scorecard": {k: scorecard.get(k) for k in DIM_ORDER + ["overall"]},
        "deltas": deltas,
        "priority_actions": [
            {"title": a["title"], "status": a["status"],
             "priority": a["priority_score"], "dimension": a["dimension"]}
            for a in recs.get("priority_actions", [])
        ],
        "watch_items": [
            {"title": wa["title"], "status": wa["status"]}
            for wa in recs.get("watch_items", [])
        ],
        "active_recommendations": sum(
            1 for r in recs.get("all_recs", [])
            if r.get("status") not in ("resolved", "dropped", "completed")),
    }


def write_monthly_csv_row(venue_name, month_str, scorecard, csv_path):
    fields = ["month", "venue"] + DIM_ORDER + ["overall"]
    row = {"month": month_str, "venue": venue_name}
    for dim in DIM_ORDER + ["overall"]:
        row[dim] = scorecard.get(dim)
    write_header = not os.path.exists(csv_path)
    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        if write_header:
            writer.writeheader()
        writer.writerow(row)


# ---------------------------------------------------------------------------
# Quarterly
# ---------------------------------------------------------------------------

def generate_quarterly_report(venue_name, quarter_str, monthly_cards, recs_history):
    L = []
    w = L.append
    w(f"# Quarterly Strategic Review — {venue_name}")
    w(f"*{quarter_str} | DayDine Premium*\n---\n")
    months = sorted(monthly_cards.keys())
    if not months:
        w("*No monthly data available.*")
        return "\n".join(L)
    w("## Dimension Trends\n")
    w("| Dimension | " + " | ".join(months) + " | Trend |")
    w("|-----------|" + "|".join(["------:" for _ in months]) + "|-------|")
    for dim in DIM_ORDER + ["overall"]:
        vals = [monthly_cards[m].get(dim) for m in months]
        strs = [f"{v:.1f}" if v is not None else "—" for v in vals]
        avail = [v for v in vals if v is not None]
        trend = "—"
        if len(avail) >= 2:
            d = avail[-1] - avail[0]
            trend = "▲" if d > 0.3 else "▼" if d < -0.3 else "→"
        w(f"| {dim.title()} | " + " | ".join(strs) + f" | {trend} |")
    w("")
    if recs_history:
        w("## Recommendation Outcomes\n")
        res = sum(1 for r in recs_history if r.get("status") in ("resolved", "completed"))
        act = sum(1 for r in recs_history if r.get("status") in ("new", "ongoing", "escalated"))
        w(f"- **{res}** resolved/completed, **{act}** still active")
    w(f"\n*DayDine Operator Intelligence v2.0*")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Conditional blocks
# ---------------------------------------------------------------------------

def generate_conditional_blocks(venue, scorecard, benchmarks):
    blocks = []
    ring1 = benchmarks.get("ring1_local", {}) if benchmarks else {}
    if ring1.get("peer_count", 0) >= 10:
        blocks.append({"title": "Competitive Density Alert",
            "content": f"{ring1['peer_count']} direct competitors within 5mi. Differentiation critical."})
    fsa = scorecard.get("fsa_rating")
    if fsa is not None and int(fsa) <= 3:
        blocks.append({"title": "Compliance Risk",
            "content": f"FSA {fsa} caps Trust score and may suppress Google visibility."})
    vis = scorecard.get("visibility")
    if vis is not None and vis < 4.0:
        blocks.append({"title": "Visibility Gap",
            "content": "Online visibility significantly below average. Prioritise GBP and reviews."})
    return blocks
